networks:
  benchmark:

services:


  android-world-env-1:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-1
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-1:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-1
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-1:5000 --device android-world-env-1:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-1

  android-world-env-2:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-2
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-2:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-2
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-2:5000 --device android-world-env-2:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-2

  android-world-env-3:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-3
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-3:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-3
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-3:5000 --device android-world-env-3:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-3

  android-world-env-4:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-4
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-4:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-4
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-4:5000 --device android-world-env-4:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-4

  android-world-env-5:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-5
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-5:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-5
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-5:5000 --device android-world-env-5:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-5

  android-world-env-6:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-6
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-6:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-6
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-6:5000 --device android-world-env-6:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-6

  android-world-env-7:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-7
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-7:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-7
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-7:5000 --device android-world-env-7:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-7

  android-world-env-8:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-8
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-8:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-8
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-8:5000 --device android-world-env-8:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-8

  android-world-env-9:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-9
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-9:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-9
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-9:5000 --device android-world-env-9:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-9

  android-world-env-10:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-10
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-10:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-10
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-10:5000 --device android-world-env-10:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-10

  ws-scrcpy:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/ws-scrcpy:latest
    container_name: ws-scrcpy
    networks:
      - benchmark
    environment:
      - ADB_DEVICES=android-world-env-1:5555,android-world-env-2:5555,android-world-env-3:5555,android-world-env-4:5555,android-world-env-5:5555,android-world-env-6:5555,android-world-env-7:5555,android-world-env-8:5555,android-world-env-9:5555,android-world-env-10:5555
    ports:
      - 8000:8080

