services:
  traefik:
    image: traefik:3.4
    command:
      - --configFile=/etc/traefik/traefik.yml
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
      - ./certs:/certs
    networks:
      - benchmark
    ports:
      - "80:80"
      - "443:443"
    labels:
      #traefik dashboard + API.
      traefik.enable: false
      #traefik.http.routers.dashboard.rule: Host(`benchmark-proxy.droidrun.ai`)
      #traefik.http.routers.dashboard.service: api@internal
      #traefik.http.routers.dashboard.middlewares: proxy-google-auth@file
  android-world-env-1:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-1
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-1:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-1
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-1:5000 --device android-world-env-1:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --max-task-idx 39 --timeout-multiplier 1000
    depends_on:
      - android-world-env-1

  android-world-env-2:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-2
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-2:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-2
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-2:5000 --device android-world-env-2:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 40 --max-task-idx 79 --timeout-multiplier 1000
    depends_on:
      - android-world-env-2

  android-world-env-3:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/android-world:latest
    container_name: android-world-env-3
    privileged: true
    networks:
      - benchmark
  droidrun-benchmark-3:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/droidrun-android-world:latest
    container_name: droidrun-benchmark-3
    networks:
      - benchmark
    volumes:
      - ./eval_results:/opt/shared/eval_results
    env_file:
      - .env
    command: --base-url http://android-world-env-3:5000 --device android-world-env-3:5555 --llm-provider Gemini --llm-model models/gemini-2.5-pro --debug --reasoning --min-task-idx 80 --max-task-idx 117 --timeout-multiplier 1000
    depends_on:
      - android-world-env-3

  ws-scrcpy:
    image: europe-west3-docker.pkg.dev/bonny-android-use-staging/droidrun/ws-scrcpy:latest
    container_name: ws-scrcpy
    networks:
      - benchmark
    labels:
      traefik.enable: true
      traefik.http.routers.ws-scrcpy.rule: Host(`supervisor.droidrun.ai`)
      traefik.http.routers.ws-scrcpy.middlewares: proxy-google-auth@file
    environment:
      - ADB_DEVICES=android-world-env-1:5555,android-world-env-2:5555,android-world-env-3:5555


networks:
  benchmark:
